"""empty message

Revision ID: 2eb9cb42b6f6
Revises: 2e8b64c48f50
Create Date: 2020-04-26 16:31:19.738002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eb9cb42b6f6'
down_revision = '2e8b64c48f50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_caca_email', table_name='caca')
    op.drop_index('ix_caca_name', table_name='caca')
    op.drop_table('caca')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caca',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('sub', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='caca_pkey')
    )
    op.create_index('ix_caca_name', 'caca', ['name'], unique=True)
    op.create_index('ix_caca_email', 'caca', ['email'], unique=True)
    # ### end Alembic commands ###
