"""empty message

Revision ID: 4529c6b27b5c
Revises: f604bbe7f97e
Create Date: 2020-05-04 12:41:00.950392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4529c6b27b5c'
down_revision = 'f604bbe7f97e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=True)
    op.drop_index('ix_user_sub', table_name='user')
    op.drop_column('user', 'sub')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sub', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index('ix_user_sub', 'user', ['sub'], unique=True)
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###
