"""empty message

Revision ID: 48edcf792b69
Revises: 70a656fcdcc8
Create Date: 2020-05-13 15:41:22.532120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48edcf792b69'
down_revision = '70a656fcdcc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('last_photo_viewed', sa.String(length=100), nullable=True))
    op.add_column('album', sa.Column('last_time_viewed', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'last_time_viewed')
    op.drop_column('album', 'last_photo_viewed')
    # ### end Alembic commands ###
