"""empty message

Revision ID: f604bbe7f97e
Revises: a4352c5cb050
Create Date: 2020-05-04 12:33:40.769322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f604bbe7f97e'
down_revision = 'a4352c5cb050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('picture', sa.String(length=300), nullable=True))
    op.create_unique_constraint(None, 'user', ['picture'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'picture')
    # ### end Alembic commands ###
